### PR TITLE
adding missing env array

### PR DESCRIPTION
**Pull request by vsoch**
In addition to pre_run, post_run, and shell, a user should always be able to provide environment variables. This would be an array of strings, like:

```
my_section:
    type: "script"
    run: "echo hello ${FIRST_NAME} ${LAST_NAME}"
    env:
      - FIRST_NAME=HAROLD
      - LAST_NAME=KUMAR
```

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by vsoch** [comment]
@shahzebsiddiqui should we have a regular expression to check that each line is in the format `<name>=<var>` ? I can't think of cases when we wouldn't want that.

**Comment by vsoch** [comment]
okay just updated the PR - here is an example of how this looks now:

```yaml
# Shell would be accepted to indicate a single line shell command (or similar)
login_node_check:
  type: script
  env:
    login_node: 1 
    login_name: login
  run: "ping ${login_name} ${login_node}"
```
This is much easier to validate because we can allow any kind of value, but ensure that the keys still don't have spaces (should be honored by the global setting).

**Comment by shahzebsiddiqui** [comment]
@vsoch While you at it, you can also remove the ``__pycache__`` directory https://github.com/HPC-buildtest/schemas/tree/master/.github/tests/__pycache__

**Comment by vsoch** [comment]
Oh gosh that's embarrassing! Yes, will remove asap!

**Comment by shahzebsiddiqui** [comment]
Thanks @vsoch. Merging now

**Pull request merged**
