### PR TITLE
adding equivalent MIT license to match docstrings and buildtest

### PR DESCRIPTION
**Pull request by vsoch**
We are missing a LICENSE file here (but we have the docstrings) so I'm adding the same license as we have for buildtest. We don't have any kind of LLC so we cannot put the name of an organization, so that leaves an individual as the option. I hope it's okay I put my name for now since I'll be taking charge of most of the code here!

Signed-off-by: vsoch <vsochat@stanford.edu>

### CODE REVIEW

**Comment by shahzebsiddiqui** [comment]
Oh i see you have the LICENSE file that conflicts with #13 . Does it make sense to incorporate `2017-2020` since buildtest started in 2017. Or do we need to be picky and license this from 2020. I am fine with either way. 

Also if you had note, i don't put the license banner on each source file, its just too much work. I used to do that but doesn't make sense.

**Comment by vsoch** [comment]
No, this is not buildtest - this repository was created and written from scratch in 2020.

**Comment by vsoch** [comment]
I put the banner on repos in the case that a contributor contributes an entire file, then the file gets licensed (the same) but with credit to him/her as the copyright. If the contributor wants this, it's the easiest way to do it.

I'm confused as to why when I opened #12 you ignored it and opened #13...

**Comment by shahzebsiddiqui** [comment]
> No, this is not buildtest - this repository was created and written from scratch in 2020.

Makes sense to me.

**Pull request merged**
