### PR TITLE
adding license

### PR DESCRIPTION
**Pull request by shahzebsiddiqui**

### CODE REVIEW

**Comment by vsoch** [comment]
@shahzebsiddiqui you can't put a project name as a license, it's not a legal entity.

**Comment by shahzebsiddiqui** [comment]
> @shahzebsiddiqui you can't put a project name as a license, it's not a legal entity.

@vsoch  Its fixed now

**Comment by vsoch** [comment]
Not cool @shahzebsiddiqui  - you think it's really ok to put your name on code that I wrote? :/

**Comment by vsoch** [comment]
I already did this work, and correctly to update the test in #12. The license is the same as buildtest (MIT) so there is no issue using the schemas there.

**Comment by shahzebsiddiqui** [comment]
> Not cool @shahzebsiddiqui - you think it's really ok to put your name on code that I wrote? :/

I didn't see your PR when i was doing this. My bad :(

**Comment by vsoch** [comment]
So glad this was a misunderstanding! My heart dropped for a second. Let's pick up discussion in #12.

**Pull request closed without merging**
